# Generated by Django 3.2.9 on 2022-02-09 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='item_lister',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auctions.user'),
            preserve_default=False,
        ),
    ]
